mibew_external_api_operator_anyOperatorsOnline:
    path: /api/anyOperatorsOnline
    defaults:
        _controller: Mibew\Mibew\Plugin\ExternalApi\Controller\OperatorController::anyOperatorsOnline
    methods: [GET]
